### ISSUE TITLE
Add git hook to repo

### ISSUE THREAD

**Issue by bootstraps** [mybuddymichael/pg-dashboard#21]
Need to get with Kevin and update the git post-receive hook to post to the heroku app.

**Comment by mybuddymichael** [comment]
@bootstraps What's wrong with the hook?

**Comment by bootstraps** [comment]
Nothing yet b/c it doesn't exist. The hook it writeable only to Kevin. I have to get him to either help me add it or make it writeable. But he's out of the office for a bit so I just wanted the reminder.

**Comment by mybuddymichael** [comment]
@bootstraps I just made it group-writeable.

**Comment by bootstraps** [comment]
Awesome boss. thanks. aren't you supposed to be at the beach?

**Comment by mybuddymichael** [comment]
@bootstraps Yeah yeah...

**Comment by bootstraps** [comment]
Closing issue. git hook is added to repo, but is currently disabled due to network performance.
